#v1
project_identifier: cyclos
api_key: 07a30860dde4b164434bbf90f4350b41
# v2
project_id: 115301
api_token: 3e06772f68e1c9aaf130a6ea710932ce3c7472a1502b45a0fa6c0f213f63b9db0040219c409c810f

base_path: ../src/i18n
preserve_hierarchy: true  # creates the translations folder in the Crowdin's project

files:
  -
    source: '/i18n.json'    # the translations for the frontend
    translation: '/%file_name%.%osx_locale%.%file_extension%'
    escape_quotes: 0  # do not escape single quote. We must set this option because default value is 3
    languages_mapping:
      osx_locale:          # crowdin_language_code: local_name
        'es-ES': 'es'
        'pt-PT': 'pt'
        'zh-CN': 'zh'
        'id': 'in'
        'he': 'iw'
